app = "stock-prediction-123"  # 替换为唯一名字
primary_region = "nrt"  # 东京节点，国内访问快，可选其他（如"ord"芝加哥）

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1